### ISSUE TITLE
Plate cropping & number recognition

### ISSUE THREAD

**Issue by ubuntu204** [muratali016/Yolov7-License-Plate-Recognition-Program#1]
Thank you @muratali016 for this interesting work.

Once plate super-resolution is generated, you did not provide any numbers & characters recognition, right?

**Comment by muratali016** [comment]
Hello @ubuntu204,
there is no numbers & characters recognition. Just saves the high-resolution images to the database

**Comment by ubuntu204** [comment]
Hi @muratali016 
which database?
I can see that the high-resolution images are being saved to yolov7/Real-ESRGAN/results but not inserted into any database.

**Comment by muratali016** [comment]
> @ubuntu204 
Yeah, I'm using that folder as the database of license plate images. That folder is located in my Google Drive
