### ISSUE TITLE
Detect whole frame and not only yellow line

### ISSUE THREAD

**Issue by ubuntu204** [muratali016/Yolov7-License-Plate-Recognition-Program#2]
Hi @muratali016 

Can you please show me how to make changes to the detect_plate.py to detect all moving cars in the frame and not only those crossing the line?

Thanks

**Comment by muratali016** [comment]
@ubuntu204 
can you please check the link: https://github.com/muratali016/Yolov7-Object-Counter-Custom-Funcitons/blob/main/detect_and_count.py
 That script does exactly what you mention
There is a function in this script : "def count()", that's what you need.

**Comment by ubuntu204** [comment]
thank you @muratali016..
I was able to successfully use your provided detect_and_count script
is the detected objects BB saved somewhere?

**Comment by muratali016** [comment]
@ubuntu204 in that file, bb images are not saving
. To save bb you can use that file:https://www.github.com/muratali016/Yolov7-Object-Counter-Custom-Funcitons/tree/main/save_bounding_boxes_images.py
